name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RACK_DIR: ./Rack

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    
    - uses: actions/checkout@v5
      with:
        repository: VCVRack/Rack
        submodules: recursive
        path: ./Rack
        
    - name: Build
      run: make
