name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RACK_DIR: ${GITHUB_WORKSPACE}/Rack

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install apt dependencies
      run: sudo apt install -y unzip git curl cmake libx11-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev zlib1g-dev libasound2-dev libgtk2.0-dev libgtk-3-dev libjack-jackd2-dev jq zstd libpulse-dev pkg-config libjansson-dev

    - uses: actions/checkout@v5
    
    - name: Cache Rack dependency
      id: checkout-rack
      uses: actions/cache@v4
      with:
        path: ${GITHUB_WORKSPACE}/Rack/
        key: rack-folder

    - name: Checkout Rack
      if: steps.checkout-rack.outputs.cache-hit != 'true'
      uses: actions/checkout@v5
      with:
        repository: VCVRack/Rack
        lfs: true
        path: ./Rack
        submodules: recursive

    - name: Fetch built dependencies
      id: cached-dep
      uses: actions/cache@v4
      with:
        path: ./Rack/deps
        key: rack-deps

    - name: Build dependencies
      id: build-dependencies
      if: steps.cached-dep.outputs.cache-hit != 'true'
      working-directory: ${GITHUB_WORKSPACE}/Rack
      run: make dep

    - name: Build
      run: make
